feature: Add action move-issue-after-review
superdispatch/actions pull request #79
Opened 2023-05-03 12:22 UTC by geekkun

2023-05-03 14:47 UTC, timurhamitov commented on package-lock.json
@geekkun We are using Yarn instead of NPM. That's why this file was generated. You can remove this file and run `yarn` command if the Yarn is installed.  Let me know if you need help with fixing this=)

2023-05-03 15:00 UTC, timurhamitov commented on jira/move-issue-after-review/index.ts
> +        Reflect.deleteProperty(filteredChangesRequested, review.user.login);
@geekkun We usually not using `Reflect` API, so I'm not sure how reasonable to use it here. 
What do you think about using [`Map` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) instead of a plain JS object?

2023-05-03 15:06 UTC, timurhamitov commented on jira/README.md
@geekkun Thank you!

2023-05-03 16:02 UTC, geekkun commented on jira/move-issue-after-review/index.ts
> +        Reflect.deleteProperty(filteredChangesRequested, review.user.login);
@timurhamitov please have a look, possibly changed according to your suggestions :)

2023-05-03 16:09 UTC, doniyor2109 commented
@geekkun Can we add filter for this action so we can control which team it will work? Because if we are going to add this action then all teams will be using it. 

So I recommend to add ability to experiment with one team first.

2023-05-03 19:42 UTC, geekkun commented
@doniyor2109 I will add team filtering for experiment stage, but actually it will be useless if only one team (in CM) would use it. It won't solve a problem when there is untested code on staging during the evening/night and it blocks release of fixes. That's the main goal and we are getting into agreement with Python and QA chapter.

2023-05-05 13:47 UTC, doniyor2109 requested changes

2023-05-05 13:47 UTC, doniyor2109 commented on jira/pr-review/index.ts
> +    );
lets stop action here if this condition matches.
You can use `return` statement for that

2023-05-05 13:47 UTC, doniyor2109 commented on jira/pr-review/action.yml
> +  seniors:
Maybe we can call it `reviewers`?

2023-05-06 11:02 UTC, timurhamitov commented on jira/move-issue-after-review/index.ts
> +        Reflect.deleteProperty(filteredChangesRequested, review.user.login);
@geekkun Looks great!

2023-05-09 10:40 UTC, doniyor2109 commented on jira/pr-review/index.ts
> +    info(`Cannot transition "${issue.key}" to "${transitionTarget}".`);
@geekkun Got you. I think it should not raise error. It is logger and we can mark it as error log.

2023-05-12 09:33 UTC, doniyor2109 approved these changes

2023-05-12 09:37 UTC, doniyor2109 commented
@geekkun I think some files are generated because of NPM packages.
Can you exclude all js files from your commits?

2023-05-12 10:16 UTC, merged