Add label by Jira issue type if it is exists
superdispatch/actions pull request #81
Opened 2023-06-26 05:40 UTC by uchqunbek

2023-07-03 07:54 UTC, doniyor2109 requested changes

2023-07-03 07:54 UTC, doniyor2109 commented
> @doniyor2109 how I can fix the failed PR check?

Fixed checks

2023-07-05 09:35 UTC, uchqunbek commented on jira/add-project-label/index.ts
> +        labelsToAdd.push(labelName);
@doniyor2109 I wanted to add a label only if it exists in the repository. So in this case any other repositories without existing labels won't be affected. Do you think creating a label is a better choice?

2023-07-10 05:06 UTC, uchqunbek commented on jira/add-project-label/index.ts
> +        labelsToAdd.push(labelName);
@doniyor2109 Updated

2023-07-10 05:13 UTC, doniyor2109 commented on jira/add-project-label/index.ts
> +    }
I think we should check for issueLabel as well in if condition

2023-07-10 12:11 UTC, doniyor2109 approved these changes

2023-07-10 12:24 UTC, merged